// generated by Fast Light User Interface Designer (fluid) version 1.0304
#pragma once

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>

class GUI {
public:
	GUI();
	Fl_Double_Window *uiw;
private:
	inline void cb_LoadTiffButton_i(Fl_Button*, void*);
	static void cb_LoadTiffButton(Fl_Button*, void*);
	inline void cb_SaveTiffButton_i(Fl_Button*, void*);
	static void cb_SaveTiffButton(Fl_Button*, void*);
	inline void cb_Play_i(Fl_Return_Button*, void*);
	static void cb_Play(Fl_Return_Button*, void*);
public:
	void show();
	void LoadTiffButton_cb();
	void SaveTiffButton_cb();
	void Play_cb();
};