// generated by Fast Light User Interface Designer (fluid) version 1.0304
#pragma once

#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>

class GUI {
public:
	GUI();
	Fl_Double_Window *uiw;
private:
	void cb_LoadTxtButton_i(Fl_Button*, void*);
	static void cb_LoadTxtButton(Fl_Button*, void*);
	void cb_SaveTxtButton_i(Fl_Button*, void*);
	static void cb_SaveTxtButton(Fl_Button*, void*);

	void cb_LoadBinButton_i(Fl_Button*, void*);
	static void cb_LoadBinButton(Fl_Button*, void*);
	void cb_SaveBinButton_i(Fl_Button*, void*);
	static void cb_SaveBinButton(Fl_Button*, void*);
	void cb_TeapotButton_i(Fl_Button*, void*);
	static void cb_TeapotButton(Fl_Button*, void*);

	void cb_RotationButton_i(Fl_Button*, void*);
	static void cb_RotationButton(Fl_Button*, void*);

	void cb_Play_i(Fl_Return_Button*, void*);
	static void cb_Play(Fl_Return_Button*, void*);

	void cb_LightLeftButton_i(Fl_Return_Button*, void*);
	static void cb_LightLeftButton(Fl_Return_Button*, void*);
	void cb_LightRightButton_i(Fl_Return_Button*, void*);
	static void cb_LightRightButton(Fl_Return_Button*, void*);
	void cb_LightUpButton_i(Fl_Return_Button*, void*);
	static void cb_LightUpButton(Fl_Return_Button*, void*);
	void cb_LightDownButton_i(Fl_Return_Button*, void*);
	static void cb_LightDownButton(Fl_Return_Button*, void*);
	void cb_LightFrontButton_i(Fl_Return_Button*, void*);
	static void cb_LightFrontButton(Fl_Return_Button*, void*);
	void cb_LightBackButton_i(Fl_Return_Button*, void*);
	static void cb_LightBackButton(Fl_Return_Button*, void*);

	void cb_LightIncExponentButton_i(Fl_Return_Button*, void*);
	static void cb_LightIncExponentButton(Fl_Return_Button*, void*);
	void cb_LightDecExponentButton_i(Fl_Return_Button*, void*);
	static void cb_LightDecExponentButton(Fl_Return_Button*, void*);

	void cb_LightIncAmbientButton_i(Fl_Return_Button*, void*);
	static void cb_LightIncAmbientButton(Fl_Return_Button*, void*);
	void cb_LightDecAmbientButton_i(Fl_Return_Button*, void*);
	static void cb_LightDecAmbientButton(Fl_Return_Button*, void*);

	void cb_SM1Button_i(Fl_Return_Button*, void*);
	static void cb_SM1Button(Fl_Return_Button*, void*);
	void cb_SM2Button_i(Fl_Return_Button*, void*);
	static void cb_SM2Button(Fl_Return_Button*, void*);
	void cb_SM3Button_i(Fl_Return_Button*, void*);
	static void cb_SM3Button(Fl_Return_Button*, void*);

public:
	void show();
	void LoadTxtButton_cb();
	void SaveTxtButton_cb();
	void LoadBinButton_cb();
	void SaveBinButton_cb();
	void RotationButton_cb();
	void TeapotButton_cb();

	void Play_cb();

	void LightLeftButton_cb();
	void LightRightButton_cb();
	void LightUpButton_cb();
	void LightDownButton_cb();
	void LightFrontButton_cb();
	void LightBackButton_cb();

	void LightIncExponentButton_cb();
	void LightDecExponentButton_cb();
	void LightIncAmbientButton_cb();
	void LightDecAmbientButton_cb();

	void SM1Button_cb();
	void SM2Button_cb();
	void SM3Button_cb();
};