// generated by Fast Light User Interface Designer (fluid) version 1.0304
#include "gui.hpp"
#include "scene.hpp"

void GUI::cb_LoadTxtButton_i(Fl_Button*, void*) {
    LoadTxtButton_cb();
}

void GUI::cb_LoadTxtButton(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_LoadTxtButton_i(o,v);
}

void GUI::cb_SaveTxtButton_i(Fl_Button*, void*) {
    SaveTxtButton_cb();
}

void GUI::cb_SaveTxtButton(Fl_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_SaveTxtButton_i(o, v);
}

void GUI::cb_Play_i(Fl_Return_Button*, void*) {
    Play_cb();
}

void GUI::cb_Play(Fl_Return_Button* o, void* v) {
    ((GUI*)(o->parent()->user_data()))->cb_Play_i(o,v);
}

GUI::GUI() {
    {
        uiw = new Fl_Double_Window(199, 197, "GUI");
        uiw->user_data((void*)(this));
        {
            Fl_Button* o = new Fl_Button(15, 15, 150, 50, "Load Txt");
            o->selection_color(FL_DARK_RED);
            o->callback((Fl_Callback*)cb_LoadTxtButton);
        } // Fl_Button* o
        {
            Fl_Button* o = new Fl_Button(15, 80, 150, 50, "Save Txt");
            o->selection_color(FL_DARK_RED);
            o->callback((Fl_Callback*)cb_SaveTxtButton);
        } // Fl_Button* o
        {
            Fl_Button* o = new Fl_Button(15, 145, 150, 50, "Play");
            o->callback((Fl_Callback*)cb_Play);
        } // Fl_Return_Button* o
        uiw->end();
    } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
    scene = new Scene;
    return Fl::run();
}

void GUI::show() {
    uiw->show();
}

void GUI::LoadTxtButton_cb() {
    scene->LoadTxtButton();
}

void GUI::SaveTxtButton_cb() {
    scene->SaveTxtButton();
}

void GUI::Play_cb() {
    scene->TransitionCamera();
}